name: CI & Releasing

on:
  push:
    branches: [main]

permissions:
  contents: read # read files

jobs:
  fmt:
    runs-on:
      size: 2x8
      image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260401-2

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check Formatting
        run: cargo fmt --all --check

  dev:
    runs-on:
      size: 2x8
      image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260401-2

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-workspace-crates: true
          prefix-key: v1-rust

      - parallel:
          - name: Lint
            run: task lint

          - name: Test
            run: task test

  build:
    runs-on:
      size: 2x8
      image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260401-2

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-workspace-crates: true
          prefix-key: v1-rust

      - name: Build
        run: task build:release

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release-build-${{ runner.os }}
          path: |
            target/release/godot_spacemouse.dll
            target/release/libgodot_spacemouse.dylib
            target/release/libgodot_spacemouse.so

  release:
    needs: [dev, build]
    runs-on: depot-ubuntu-24.04
      #size: 2x8
      #image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260330

    permissions:
      contents: write # Create tags and releases
      pull-requests: write # Create and update release PRs
      discussions: write # Open GitHub Discussions (optional)

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: release-build-*
          merge-multiple: true

      - name: list files
        run: ls -R

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          add-job-id-key: false
          shared-key: v1-sampo

      - name: Run Sampo Release/Publish Action
        id: sampo
        uses: bruits/sampo/crates/sampo-github-action@438b2ebfb4a78c1b8c2fe3a3da8c825cb21c6131 # v0.15.0
        with:
          create-github-release: true
          #release-assets: blah/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }} # For Cargo packages (optional)
