name: CI & Releasing

on:
  push:
    branches: [main]

permissions:
  contents: read # read files

jobs:
  fmt:
    runs-on: depot-ubuntu-24.04
      #size: 2x8
      #image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260330

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Rust
        uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          components: rustfmt

      - name: Check Formatting
        run: cargo fmt --all --check

  dev:
    runs-on: depot-ubuntu-24.04
      #size: 2x8
      #image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260330

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2

      - name: Set Minimal Profile
        run: rustup set profile minimal

      - name: Install Clippy
        run: rustup component add clippy

      - uses: cargo-bins/cargo-binstall@0b24824336e2b3800b0f89d9e08b2c08bfa3dcdd # v1.17.9
        with:
          version: "1.17.9" # optional; defaults to latest
      - run: cargo binstall cargo-nextest@0.9.132

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-workspace-crates: true
          prefix-key: v1-rust

      - parallel:
          - name: Lint
            run: task lint

          - name: Test
            run: task test

  build:
    runs-on: depot-ubuntu-24.04
      #size: 2x8
      #image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260330

    strategy:
      fail-fast: false
      matrix:
        os:
          - depot-ubuntu-24.04
          - depot-windows-2022-4
          - depot-macos-15

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2

      - name: Set Minimal Profile
        run: rustup set profile minimal

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-workspace-crates: true
          prefix-key: v1-rust

      - name: Build
        run: task build:release

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release-build-${{ runner.os }}
          path: |
            target/release/godot_spacemouse.dll
            target/release/libgodot_spacemouse.dylib
            target/release/libgodot_spacemouse.so

  release:
    needs: [dev, build]
    runs-on: depot-ubuntu-24.04
      #size: 2x8
      #image: v3pngn245j.registry.depot.dev/spacemouse-rs:1.94.1-20260330

    permissions:
      contents: write # Create tags and releases
      pull-requests: write # Create and update release PRs
      discussions: write # Open GitHub Discussions (optional)

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          pattern: release-build-*
          merge-multiple: true

      - name: list files
        run: ls -R target/release

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          add-job-id-key: false
          shared-key: v1-sampo

      - name: Run Sampo Release/Publish Action
        id: sampo
        uses: bruits/sampo/crates/sampo-github-action@438b2ebfb4a78c1b8c2fe3a3da8c825cb21c6131 # v0.15.0
        with:
          create-github-release: true
          #release-assets: blah/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }} # For Cargo packages (optional)
