name: Release & Publish

on:
  push:
    branches: [main]

permissions:
  contents: read # read files

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write # Create tags and releases
      pull-requests: write # Create and update release PRs
      discussions: write # Open GitHub Discussions (optional)
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run Sampo Release/Publish Action
        id: sampo
        uses: bruits/sampo/crates/sampo-github-action@e5ec8f6631c860baa2e7ad9ef156a29b0838d69a # v0.13.0
        with:
          create-github-release: true
          #release-assets: blah/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }} # For Cargo packages (optional)
